//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROLINSA_SISTEMA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleProducto
    {
        public int IdProducto { get; set; }
        public string NombreProveedor { get; set; }
        public string PaisProveedor { get; set; }
        public string TelefonoProveedor { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public string FechaCompra { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Proveedores Proveedores { get; set; }
    }
}
